config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[show new create] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: %i[destroy]
  
  root to: 'cocktails#index' 
end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_one_attached :photo
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    validates :name, presence: true ,uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  
  validates :description, presence: true
  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses 
    
    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    # listagem de todos os cocktails
    @cocktails = Cocktail.all
  end

  def show
    # detalhes de UM cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def new
    # pagina de formulario para criar um novo cocktail
    @cocktail = Cocktail.new
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)

    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<!--This website has been created as a developer process
  All the contains are ilustrative. In case of interesting,
  please do not hesitate to contact me-->

<!-------Main Page------>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="banner">
    <div class="container mt-5 d-flex">
      <h1>Drink Generator</h1>
    </div>

    <!--List of Drinks ---->

    <div class="container mt-5 d-flex text-align:center">
      <ul>
        <% @cocktails.each do |cocktail| %>
          <li>
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </li>
        <% end %>

    <!---Button for generate the drink ---->

        <%= link_to "Make your Drink", new_cocktail_path, class: "btn btn-primary mt-2" %>
      </ul>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<!--This website has been created as a developer process
  All the contains are ilustrative. In case of interesting,
  please do not hesitate to contact me-->

<!-- Where the drink will be generate -->

<div class="container mt-5 d-flex">
  <h1>Make here</h1>
</div>


<!-- Field for user input -->

<div class="menu mt-5 d-flex">
  <ul>
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.submit class: "btn btn-primary mt-2"%>
    <% end %>
  </ul>
</div>

app/views/cocktails/show.html.erb
<!--This website has been created as a developer process
  All the contains are ilustrative. In case of interesting,
  please do not hesitate to contact me-->

<!-- Result and create a new drink!! -->

<div class="container mt-5 d-flex">
  <h1>Esse é o drink: <%= @cocktail.name %></h1>
</div>


  <ul>
     <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.description %> <%= dose.ingredient.name %> <%= link_to "remova essa dose", dose_path(dose), method: :delete %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Crie a sua dose!", new_cocktail_dose_path(@cocktail)%>

app/views/doses/new.html.erb
<h1>Crie uma nova dose</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>